# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0043_auto_20181129_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomThought',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Post')),
            ],
            options={
                'verbose_name': 'Random Thought',
            },
            bases=('home.post',),
        ),
    ]
