# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_thought', '0003_allrandomthoughtshomepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allrandomthoughtshomepage',
            options={'verbose_name': 'Random Thoughts Homepage'},
        ),
    ]
